name: Deploy to PPE

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  checks:
    name: Checks
    uses: ./.github/workflows/checks.yml

  build:
    name: Build and Deploy
    needs: checks
    runs-on: ubuntu-latest
    env:
      AZURE_WEBAPP_NAME: malservice
      SLOT_NAME: ppe
    steps:
      - uses: actions/checkout@v7
      - uses: azure/docker-login@v2
        with:
          login-server: malcontainerregistry.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t malcontainerregistry.azurecr.io/${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }}
          docker push malcontainerregistry.azurecr.io/${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }}
      - uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.PPE_PUBLISH_PROFILE }}
          slot-name: ${{ env.SLOT_NAME }}
          images: malcontainerregistry.azurecr.io/${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }}
